---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cte-csi-node
  namespace: {{ .Values.namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cte-csi-node-ac
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "watch", "get"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "list", "delete", "get", "patch"]

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch"]

  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "patch"]

  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]

  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "patch"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes", "storageclasses"]
    verbs: ["get", "list", "watch", "patch"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "patch"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]

  - apiGroups: ["", "apps"]
    resources: ["daemonsets", "deployments", "replicasets", "events", "replicationcontrollers", "services", "pods/log"]
    verbs: ["get", "list"]

  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames: ["cte-csi-scc"]
    verbs: ["use"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cte-csi-node-binding
subjects:
  - kind: ServiceAccount
    name: cte-csi-node
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: cte-csi-node-ac
  apiGroup: rbac.authorization.k8s.io
