# Default values for csi-deploy-chart.

replicaCount: 1

namespace: "kube-system"

image:
  cteCsiImage: "docker.io/thalesciphertrust/ciphertrust-transparent-encryption-kubernetes"
  cteCsiTag: "1.1.0-latest"
  pullPolicy: Always
  logLevel: "1"
  pauseImage: "k8s.gcr.io/pause:latest"

imagePullSecrets: cte-csi-image-pull-secret

APIServerThrottle:
  burst: 300
  qps: 200

# Time interval for monitoring Pending Unregistration
# Integer value in minutes. Default is 10 minutes.
RegistrationCleanupInterval: 10
