apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ctek8soperator-catalog
  namespace: kube-system
spec:
  secrets:
    - cte-csi-secret
  displayName: Ciphertrust Transparent Encryption for Kubernetes Operator Catalog
  publisher: Thales DIS CPL
  sourceType: grpc
  image: "805182230944.dkr.ecr.us-east-1.amazonaws.com/ciphertrust-transparent-encryption-kubernetes-operator-catalog:v1.2.5"
  updateStrategy:
    registryPoll:
      interval: 1h
